channels:
  - fbriol
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - pillow
  - earthengine-api
  - gdal=2.3.3
  - pandas
  - geopandas
  - pytz
  - scikit-image
  - scikit-learn
  - shapely
  - scipy
  - astropy
  - spyder
  - notebook
  - seaborn
  - glob2
  - fes